#  http://localhost:8080/api/content

# // Method: POST
# POST http://localhost:8080/api/content HTTP/1.1
# content-type: application/json

# {
#   "title": "Test",
#   "description": "Test",
# }

POST http://localhost:8080/api/content HTTP/1.1
content-type: application/json

  {
    "id": 5,
    "title": "Fith Content",
    "description": "This is the fith content",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2024-11-16T14:01:54.4706256",
    "dateUpdated": null,
    "url": "https://www.google.com"
  }