
POST http://localhost:5000/api/content HTTP/1.1
content-type: application/json

  {
    "title": "Sixth Content",
    "description": "This is the fith content",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2021-09-01T00:00:00Z",
    "dateUpdated": null,
    "url": "https://www.google.com"
  }