CREATE DATABASE IF NOT EXISTS `content_db` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS content (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status ENUM('IDEA', 'IN_PROGRESS', 'COMPLETED', 'PUBLISHED') NOT NULL,
    content_type ENUM('ARTICLE', 'VIDEO', 'PODCAST', 'EVENT') NOT NULL,
    date_created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    url VARCHAR(255)
);

